#!/bin/bash

#######
# job #
#######

## Substitute with your project name:
#SBATCH --account=NN9376K

#SBATCH --job-name=template_based_docking

# the job will run for a maximum 3 hours
#              d-hh:mm:ss
#SBATCH --time=0-00:15:00

#SBATCH --output=slurm_outputs/template_based_docking_slurm_output.out

#SBATCH --qos=devel

##SBATCH --nodes=1

#SBATCH --cpus-per-task=1

#SBATCH --mem-per-cpu=1G

# you must not place bash commands before the last #SBATCH directive

## Set safer defaults for bash

set -o errexit
set -o nounset

module --quiet purge  # Clear any inherited modules

python test.py #dock_all_against_all_cl.py
