#!/bin/bash

#######
# job #
#######

## Substitute with your project name:
#SBATCH --account=NN9376K

#SBATCH --job-name=docking_P49356

#              d-hh:mm:ss
#SBATCH --time=0-00:12:00

#SBATCH --output=slurm_outputs/docking_P49356_slurm_output.out

#SBATCH --cpus-per-task=9

#SBATCH --mem-per-cpu=2G

# you must not place bash commands before the last #SBATCH directive

## Set safer defaults for bash

set -o errexit
set -o nounset

module --quiet purge  # Clear any inherited modules

python dock_all_against_all_cl.py P49356